Add tests' cases for wallet interface
GoRunMaxim/Wallet pull request #1
Opened 2020-12-11 06:51 UTC by GoRunMaxim

2020-12-11 08:40 UTC, papahmsolo requested changes
- Add `.gitignore`, `readme`, `go.mod`
- Don't forget to run `golint`, it should complain about the comments

2020-12-11 08:40 UTC, papahmsolo commented on wallet.go
> +type Wallet interface {
Interfaces are about behavior, does wallet express behaior?

2020-12-11 08:40 UTC, papahmsolo commented on wallet.go
> +	errorBalance = errors.New("not enough money")
Read Efferctive Go about errors naming convention and think about why would you want to make these errors exported or unexported.

2020-12-11 08:40 UTC, papahmsolo commented on wallet.go
> +func (ds *DataStore) Depose(bitcoin Bitcoin) error{
`Deposit`

2020-12-11 08:40 UTC, papahmsolo commented on wallet.go
> +func (ds *DataStore) Depose(bitcoin Bitcoin) error{
`DataStore` is something like DB, we're implementing a bitcoin wallet, aren't we?

2020-12-11 08:40 UTC, papahmsolo commented on wallet.go
> +	if float64(ds.bt) - math.Abs(float64(bitcoin))<0{
I think `Abs()` is redundant, can bitcoin value be negative?

2020-12-11 08:40 UTC, papahmsolo commented on wallet_test.go
> +	var ds DataStore
Short variable assignment would be preferrable here

2020-12-11 08:40 UTC, papahmsolo commented on wallet_test.go
> +	ds.bt = 0
Do we need to set `bt` explicitly to zero?

2020-12-11 09:33 UTC, GoRunMaxim commented on wallet.go
> +	if float64(ds.bt) - math.Abs(float64(bitcoin))<0{
Bitcoin is a variable that comes outside. We cannot be sure that input data will be valid

2020-12-11 10:18 UTC, papahmsolo requested changes

2020-12-11 10:18 UTC, papahmsolo commented on wallet.go
> +)
- By convention, errors start with `Err` prefix.
- Choosing meaningful names for variables improves code readability. `ErrorBalance` - what's wrong with the balance? `ErrorInput` - why input is invalid?

2020-12-11 10:18 UTC, papahmsolo commented on wallet.go
> +}
That's just my opinion, deleting new lines would make code compact and more readable. Look at the code in go standard library.

2020-12-11 10:22 UTC, papahmsolo commented on wallet.go
> +	if float64(ds.bt) - math.Abs(float64(bitcoin))<0{
@GoRunMaxim can a negative bitcoin value ever reach this code? 😃

2020-12-11 10:55 UTC, papahmsolo requested changes

2020-12-11 10:55 UTC, papahmsolo commented on wallet.go
> +	ErrNegativeBitInput = errors.New("bitcoin value error")
`not enough money` is good, it explains why the error occurred, `bitcoin value error` on the contrary does not, give more details

2020-12-11 10:57 UTC, GoRunMaxim commented on wallet.go
> +	if float64(ds.bt) - math.Abs(float64(bitcoin))<0{
My bad. I already check input data for negative value 🙃

2020-12-11 11:06 UTC, GoRunMaxim commented on wallet.go
> +	ErrNegativeBitInput = errors.New("bitcoin value error")
✅

2020-12-11 11:53 UTC, papahmsolo commented on wallet.go
> +// Bitcoin type is more readable
I'd write what is this type

2020-12-11 11:54 UTC, papahmsolo commented on wallet_test.go
> +)
Check out the `t.Run()` method to see how we can get rid of these variables and have "named" test cases instaed

2020-12-11 11:55 UTC, papahmsolo commented on wallet.go
> +// Bitcoin type is more readable
It's about Bitcoin type

2020-12-11 12:31 UTC, GoRunMaxim commented on wallet_test.go
> +)
✅

2020-12-11 12:31 UTC, GoRunMaxim commented on wallet.go
> +// Bitcoin type is more readable
✅

2020-12-11 13:27 UTC, papahmsolo commented on wallet.go
> +// Bitcoin type is more readable
Did I miss something? It's still `Bitcoin type is more readable` how about `Bitcoint represents bitcoin currency`?

2020-12-11 13:31 UTC, GoRunMaxim commented on wallet.go
> +// Bitcoin type is more readable
I thought that's its connected with error value, not with comment. Fixed now

2020-12-11 13:38 UTC, papahmsolo requested changes
Looks very good, Max!

Thoughts for further test improvement:
- Check error did not occur when you don't expect it
- Check error occurred when you expect it
- Check the balance is correct after you withdraw and deposit

2020-12-11 13:38 UTC, papahmsolo commented on wallet_test.go
> +func TestWallet_Serial(t *testing.T) {
Naming :) Don't use underscore in the func name

2020-12-11 13:38 UTC, papahmsolo commented on wallet_test.go
> +	w.bt = 40 // Cannot withdraw from zero balance
We can use a literal herer: `w := Wallet{bt: 40}`, in addition you have a `Deposit()` method to add to a wallet

2020-12-11 13:43 UTC, GoRunMaxim commented on wallet_test.go
> +func TestWallet_Serial(t *testing.T) {
✅

2020-12-14 11:06 UTC, papahmsolo requested changes
Looks good! A couple of things in comments.

2020-12-14 11:06 UTC, papahmsolo commented on wallet_test.go
> +					input:   30,
It would be a good idea to write explicitly `Bitcoin(30)`

2020-12-14 11:12 UTC, GoRunMaxim commented on wallet_test.go
> +		})
Done ✅

2020-12-14 11:22 UTC, GoRunMaxim commented on wallet_test.go
> +					input:   30,
Seems good, fixed ✅

2020-12-14 11:28 UTC, GoRunMaxim commented on wallet_test.go
> +}
Done ✅

2020-12-14 18:32 UTC, papahmsolo commented on wallet_test.go
> +}
The idea is correct: you deposit and withdraw concurrently and then check the balance is as expected. 👍 
- I'd also check `Balance()` is safe for concurrent use.
- I thought `t.Parallel()` is more for a test performance boost, rather than concurrency testing.
- This test is passing, but it's a false positive, why?

2020-12-14 18:58 UTC, papahmsolo commented on wallet.go
> +func (w *Wallet) Deposit(bitcoin Bitcoin) error {
It's idiomatic to use a short argument name, something like `b Bitcoin`

2020-12-14 19:01 UTC, GoRunMaxim commented on wallet_test.go
> +}
**This test is passing, but it's a false positive, why?**

U told about false positive. Does it means that our mutex doesn't work correctly ?

2020-12-14 19:03 UTC, GoRunMaxim commented on wallet.go
> +func (w *Wallet) Deposit(bitcoin Bitcoin) error {
✅

2020-12-14 19:06 UTC, papahmsolo commented on wallet_test.go
> +		t.Errorf("Balance missmatch. Want: [%v], got : [%v]", expected, returned)
This is not a problem at all, but it would be cool to see something like `Balance mismatch. Want: 100 BTC, but got: 99 BTC` when the test fails. To have this custom print format for `Bitcoin` type rather than using the `float64`.

2020-12-14 19:07 UTC, papahmsolo commented on wallet_test.go
> +		t.Errorf("Balance missmatch. Want: [%v], got : [%v]", expected, returned)
BTW, it's `mismatch` :)

2020-12-14 19:08 UTC, papahmsolo commented on wallet_test.go
> +}
Nope, mutex is fine

2020-12-14 19:11 UTC, papahmsolo commented on wallet_test.go
> +func assertError(expected, returned error, t *testing.T) {
Also, not an issue, but I'd pass the `t *testing.T` as a first parameter, like with `context.Context`.

2020-12-14 19:12 UTC, GoRunMaxim commented on wallet_test.go
> +		t.Errorf("Balance missmatch. Want: [%v], got : [%v]", expected, returned)
Done ✅

2020-12-14 19:15 UTC, papahmsolo commented on wallet_test.go
> +		t.Errorf("Balance mismatch. Want: %v BTC, got : %v BTC", expected, returned)
If you implement the `Stringer` interface for Bitcoin type you won't need to type `BTC` every time, formatter will do that automatically for you.

2020-12-14 19:15 UTC, papahmsolo commented on wallet_test.go
> +		t.Errorf("Balance mismatch. Want: %v BTC, got : %v BTC", expected, returned)
Again, this is not an issue, just a nice enhancement

2020-12-14 19:17 UTC, GoRunMaxim commented on wallet_test.go
> +func assertError(expected, returned error, t *testing.T) {
✅

2020-12-14 19:18 UTC, GoRunMaxim commented on wallet_test.go
> +}
So the problem connects with test case only, correct ?

2020-12-15 07:40 UTC, GoRunMaxim commented on wallet_test.go
> +		t.Errorf("Balance mismatch. Want: %v BTC, got : %v BTC", expected, returned)
✅

2020-12-15 07:52 UTC, papahmsolo commented on wallet_test.go
> +}
Shouldn't this go next to the `Bitcoin` in the `wallet.go`?

2020-12-15 07:56 UTC, papahmsolo commented on wallet_test.go
> +}
Yeah, how many times `Deposit` and `Withdraw` are actually being called?

2020-12-15 07:56 UTC, GoRunMaxim commented on wallet_test.go
> +}
Correct, fixed

2020-12-15 08:10 UTC, GoRunMaxim commented on wallet_test.go
> +}
t.Run("Parallel", func(t *testing.T) {
		for i := 0; i < 1000; i++ {
			go assertError(t, nil, w.Deposit(1))
			go assertError(t, nil, w.Withdraw(1))
		}
	})

So what about this? I think they will be called 1000 times, cuz there we don't need to "sleep" and wait all our goroutines

2020-12-15 08:14 UTC, GoRunMaxim commented on wallet_test.go
> +}
```
t.Run("Parallel", func(t *testing.T) {
		for i := 0; i < 1000; i++ {
			go assertError(t, nil, w.Deposit(1))
			go assertError(t, nil, w.Withdraw(1))
		}
	})
```

2020-12-15 09:16 UTC, papahmsolo commented on wallet_test.go
> +}
Why don't we need to wait for all goroutines? Try removing `assertError` and just call `go w.Deposit(1)` and `w.Withdraw(1)` and you'll see your test sometimes fails and sometimes succeeds.

2020-12-15 09:16 UTC, papahmsolo commented on wallet_test.go
> +
Space?

2020-12-15 09:19 UTC, papahmsolo commented on wallet_test.go
> +		t.Errorf("Balance mismatch. Want: %v, got : %v", expected, returned)
When this fails you'll get a message like this: `Balance mismatch. Want: 2000.000000 BTC, got : 1998.000000 BTC`, you can limit the number of digits after the floating point say to two by specifying the format `%.2f` in the `Bitcoin` Stringer

2020-12-15 09:24 UTC, papahmsolo commented on wallet.go
> +}
You can also embed the mutex, thus you can call `w.Lock()` and `w.Unlock()`

2020-12-15 09:29 UTC, GoRunMaxim commented on wallet_test.go
> +}
So do we need to use channels||WG in this case? Cuz time.Sleep() doesn't help

2020-12-15 09:30 UTC, GoRunMaxim commented on wallet.go
> +}
✅

2020-12-15 09:31 UTC, GoRunMaxim commented on wallet_test.go
> +		t.Errorf("Balance mismatch. Want: %v, got : %v", expected, returned)
✅

2020-12-15 13:25 UTC, GoRunMaxim commented on wallet.go
> +}
✅

2020-12-15 13:25 UTC, GoRunMaxim commented on wallet_test.go
> +		t.Errorf("Balance mismatch. Want: %v, got : %v", expected, returned)
✅

2020-12-15 13:25 UTC, GoRunMaxim commented on wallet_test.go
> +
✅

2020-12-15 13:25 UTC, GoRunMaxim commented on wallet_test.go
> +}
Fixed

2020-12-16 10:32 UTC, papahmsolo requested changes
Final notes :) Looks very good!

2020-12-16 10:32 UTC, papahmsolo commented on wallet_test.go
> +	assertBalance(t, 30, w.Balance())
Cool! A couple of ideas for improvement:
- The test is not necessarily parallel, wouldn't it be better to call it _concurrent_? There's a great talk explaining the difference https://www.youtube.com/watch?v=oV9rvDllKEg
- There's only one test here, no need for `t.Run()`
- Piggyback on my previous comment: our wallet is working with `Bitcoin` type, not with folats even though they are compatible.

2020-12-16 10:32 UTC, papahmsolo commented on wallet_test.go
> +
- I think we can have two main tests `TestWalletConcurrrent` and just `TestWallet`
- We can get rid of additional nesting with `t.Run("Wallet operations")` as all subtests will be subtests to `TestWallet`

2020-12-16 10:35 UTC, papahmsolo commented on wallet_test.go
> +	assertBalance(t, 30, w.Balance())
You can also throw in a couple of `Balance()` calls to test concurrent reads.

2020-12-16 23:23 UTC, GoRunMaxim commented on wallet_test.go
> +
✅

2020-12-17 08:27 UTC, GoRunMaxim commented on wallet_test.go
> +	assertBalance(t, 30, w.Balance())
✅

2020-12-17 08:55 UTC, papahmsolo approved these changes
Well done Max!

2020-12-17 08:55 UTC, merged